services:
  app:
    build:
      context: .
    container_name: like-button
    ports:
      - "5173:5173"
    volumes:
      - type: bind
        source: .
        target: /app
      - type: volume
        target: /app/node_modules
    stdin_open: true
    tty: true
